name: Notify AI Translation

on:
  push:
    branches:
      - ai-translation
    paths:
      - 'js/**'

jobs:
  notify-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AI translation repo
        run: |
          echo "Dispatching to AI repo..."

          response=$(curl -s -w "%{http_code}" -o response_body.txt -X POST \
            -H "Authorization: token ${{ secrets.AI_REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ac-mmi/ai-translations/dispatches \
            -d '{"event_type": "update-from-musicblocks"}')

          echo "HTTP status code: $response"
          echo "Response body:"
          cat response_body.txt

          if [ "$response" != "204" ]; then
            echo "❌ Dispatch failed"
            exit 1
          else
            echo "✅ Dispatch succeeded"
          fi
