name: Notify AI Translation

on:
  push:
    branches:
      - ai-translation   # your actual branch here
    paths:
      - 'js/**'          # only if JS files changed

jobs:
  notify-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AI translation repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.AI_REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ac-mmi/ai-translations/dispatches \
            -d '{"event_type": "update-from-musicblocks"}'
